version: "3.8"
services:
  web:
    build: web
    command: sh -c "cd egnite; gunicorn egnite.asgi:application -w 2 -b :8000 -k uvicorn.workers.UvicornWorker"
    volumes:
      - ./web/egnite:/opt/app/egnite/
      - web_static:/opt/app/static
      - web_media:/opt/app/media
    environment:
      - SECRET_KEY=8u()598=#15m64)nd&yacz+)iw&2$hgci0793m77&z=3v(8b(&

      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@gmail.com

      - REDIS_HOST=redis://redis:6379/1
      - REDIS_KEY_PREFIX=egnite

      - DATABASE_NAME=db
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432

      - EMAIL_USE_TLS=true
      - EMAIL_HOST=host
      - EMAIL_PORT=4444
      - EMAIL_HOST_USER=user
      - EMAIL_HOST_PASSWORD=password
    expose:
      - 8000
    links:
      - postgres:postgres
      - redis:redis

  nginx:
    build: nginx
    ports:
      - "80:80"
    volumes:
      - web_static:/opt/app/static
      - web_media:/opt/app/media
    links:
      - web:web

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  web_static:
  web_media:
  redis_data:
  postgres_data:
